version: "3.8"
services:
  train:
    build: .
    command: python src/train.py
    volumes:
      - ./artifacts:/app/artifacts
      - ./processed:/app/processed
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
    depends_on: []
    restart: "no"

  evaluate:
    build: .
    command: sh -c "sleep 5 && python src/evaluate.py"
    volumes:
      - ./artifacts:/app/artifacts
      - ./processed:/app/processed
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - train
    restart: "no"

  test:
    build: .
    command: sh -c "sleep 10 && pytest"
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - train
    restart: "no"

  web:
    build: .
    command: sh -c "sleep 7 && python app/app.py"
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    depends_on:
      - train
      - evaluate
    restart: "unless-stopped"